default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  # database: todo_list_production
  # username: todo_list
  password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
